### ISSUE TITLE
Function error python3#Call

### ISSUE THREAD

**Issue by Mte90** [AlphaMycelium/pathfinder.vim#30] opened 2020-06-11 10:03 UTC
I am using this code:
```
if has('python3') && has('timers')
    Plugin 'AlphaMycelium/pathfinder.vim'
endif
```
With neovim 0.5 on nvim-qt.
![immagine](https://user-images.githubusercontent.com/403283/84372457-69d55e80-abdb-11ea-89e7-39405717afea.png)

**Comment by AlphaMycelium** [comment] 2020-06-11 10:38
Duplicate of #28

**Closed** 2020-06-11 10:39 UTC
Labels: bug, duplicate
